apiVersion: v1
kind: Service
metadata:
  name: dadjokesdeploy01
  namespace: dadjokesdeploy01-ns
  labels:
    app.kubernetes.io/name: dadjokesdeploy01
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: dadjokesdeploy01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80